name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get the tag
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: google-github-actions/setup-gcloud@master
      - 
        name: Turn svc into base64
        run: |
          echo "GCP_SA_KEY_AS_BASE64=$(echo '${{ secrets.GCP_SA_KEY }}' | python -m base64)" >> $GITHUB_ENV
      # - 
      #   name: Deploy to Cloud Functions
      #   id: deploy
      #   uses: google-github-actions/deploy-cloud-functions@master
      #   with:
      #     # TODO
      # - 
      #   name: Echo URL
      #   run: echo "${{ steps.deploy.outputs.url }}"
      # - 
      #   name: Release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_REPOSITORY: langa-me/chat-example